# Generated by Django 4.2.30 on 2026-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공부 제목')),
                ('category', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('algorithm', '알고리즘'), ('database', 'Database'), ('etc', '기타')], default='django', max_length=30, verbose_name='카테고리')),
                ('study_date', models.DateField(verbose_name='공부 날짜')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='시간')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='분')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '공부 기록',
                'verbose_name_plural': '공부 기록들',
                'ordering': ['-study_date', '-created_at'],
            },
        ),
    ]
